### PR TITLE
Updated `hmt-basemodels` library

### PR DESCRIPTION
**Pull request by hugoseabra-imachines**
`hmt-basemodels` library to version `0.1.16`

### CODE REVIEW

**Review by vkomodey — CHANGES_REQUESTED** [review]
Updates for package-lock should go alongside package.json changes. The same for hmt-basemodels in the Pipfile. Let's hardcode the current version of it in the Pipfile as well

**Comment by vkomodey** [comment]
ping

**Comment by hugoseabra-imachines** [comment]
> ping

Sorry fot the delay.

> Let's hardcode the current version of it in the Pipfile as well

You mean adding fixed version `hmt-basemodels = "==0.1.16"` in Pipfile instead of `hmt-basemodels = "*"`, right?

**Comment by vkomodey** [comment]
@hugoseabra-imachines 

you have 13 commits from `master` that are already in `master`. your branch should contain only commit with your changes(delta from master)

**Comment by hugoseabra-imachines** [comment]
> @hugoseabra-imachines
> 
> you have 13 commits from `master` that are already in `master`. your branch should contain only commit with your changes(delta from master)

Yeah... the merge process again... I will close this and open a new PR. That will be easier.

**Pull request closed without merging**
