### PR TITLE
Create Harmony network support with test.

### PR DESCRIPTION
**Pull request by pmlambert**
This Pull Request includes everything to make the docker-compose tests run with the harmony network setup.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200560623420491/1201370021259535) by [Unito](https://www.unito.io)

### CODE REVIEW

**Comment by excerebrose** [comment]
@pmlambert Looking good here, why did we upgrade the truffle version though?

**Comment by pmlambert** [comment]
> @pmlambert Looking good here, why did we upgrade the truffle version though?

There is an issue with the shard number being invalid when running the test.

**Comment by posix4e** [comment]
@pmlambert have we added this to relevant scanners? Where are the smart contracts deployed?

**Comment by posix4e** [comment]
@pmlambert Why wasn’t this already merged, if it was already paid. Closing for now

**Pull request closed without merging**
