### PR TITLE
Integrate The Graph index engine

### PR DESCRIPTION
**Pull request by Charlie85270**
In this PR : 

- I added the human_subgraph repo to the human_escrow repo
- I created a script to automatically compile the ABIs from the contracts folder with `solc` 
- I updated the readme of the subgraph

@vkomodey Regarding the compilation process, for the moment ABIs are compiled when we Run/Build/Deploy the graph. 

I seen that you want trigger subgraphs recompilation via CI/CD mechanism, @ivhus can you help me with that ?

### CODE REVIEW

**Comment by posix4e** [comment]
1) resign

**Review by posix4e — CHANGES_REQUESTED** [review]
@Charlie85270 


1) re sign cla
2) collapse the subgraph code to use a single branch 
3) combine the GitHub directory CI/CD from both repos

**Comment by Charlie85270** [comment]
@posix4e 

- I collapsed the subgraph branch to use only one branch and support multiple networks. 
     - ` networks.json` file is used to centralize the networks configurations
     -  I created a TEMPLATE (subgraph.template.yaml) and a SCRIPT (generatenetworkssubgraphs.js) to automatically generate the subgraph.yaml file for each network.
     - I combined the CI/CD directory of both repo
     - I updated the hmt_subgraph CI/CD scripts to automatically launch the deployment of all subgraph when a modification is made on `contracts` or subgraph code source.
     - I updated the documentation

**Comment by Charlie85270** [comment]
This PR fix :
- https://github.com/humanprotocol/hmt-escrow/issues/333
- https://github.com/humanprotocol/humansubgraph/issues/16
- https://github.com/humanprotocol/humansubgraph/issues/7

**Pull request closed without merging**
