### PR TITLE
Query historical data from a GraphQL endpoint

### PR DESCRIPTION
**Pull request by Charlie85270**
Modified schemas and indexation to query historical data (wrt time) from a GraphQL endpoint for the following elements:

- [x]  Amount Of Escrows
Example : get escrows launched between 4 September 2022 00:00 and 5 September 2022 00:00
```
{
  launchedEscrows(
    where: {  timestamp_gte: 1662249600, timestamp_lte: 1662336000}
  ) {
    id
  }
}
```
- [x]  All Escrows Pending Events
Example : get escrows pending events between 4 September 2022 00:00 and 5 September 2022 00:00
```
{
  pevents(
    where: {  timestamp_gte: 1662249600, timestamp_lte: 1662336000}
  ) {
    id
  }
}
```
- [x]  All Escrows BulkTransfer Events
Example : get escrows bulkTransers events between 4 September 2022 00:00 and 5 September 2022 00:00
```
{
  bulkTransferEvents(
    where: {  timestamp_gte: 1662249600, timestamp_lte: 1662336000}
  ) {
    id
  }
}
```
- [x]  All Escrows Intermediate Storage Events
Example : get escrows Intermediate events between 4 September 2022 00:00 and 5 September 2022 00:00
```
{
  isevents(
    where: {  timestamp_gte: 1662249600, timestamp_lte: 1662336000}
  ) {
    id
  }
}
```

Total Number Of Escrow Events for the following networks:

- [x]  Polygon Mainnet
- [ ]  Polygon Mumbai Testnet
- [X]  Ethereum Rinkeby
- [ ]  Neons Lab Devtestnet

**Mumbai and Neons Lab Devtestnet are not yet indexed, contracts for these BC has been already deployed ?** 

Also, query the following token data:

- [X]  Token Transfers
Query to get the total of token transfers 
```
{
   hmtokenStatistics(id: "hmt-statistics-id") {
    totalTransferEventCount
  }
}
```
- [x]  Token Price **(Not indexed on the graph, must be fetch with coingecko API)**
- [x]  Token Amount of transfers
Queries to get the total value transfered 
```
{
   hmtokenStatistics(id: "hmt-statistics-id") {
    totalValueTransfered
  }
}
```
- [x]  Token Holders **(Not indexed on the graph, must be fetch with scan API)**

### CODE REVIEW

**Comment by foufrix** [comment]
@Charlie85270 is this complete on your side?

**Comment by Charlie85270** [comment]
Hey @foufrix , yes this PR is complete.

**Comment by foufrix** [comment]
@eugenvoronov possible to have a validation of everything? 🙏

**Comment by posix4e** [comment]
Please rebase first

**Comment by Charlie85270** [comment]
@posix4e  Done

**Review by posix4e — CHANGES_REQUESTED** [review]
Hey can you verify that the total number of events is the same and we don't lose some number of events with this new change? Perhaps we could add a test?

**Review by posix4e — CHANGES_REQUESTED** [review]
Why use a timestamp instead of the blocknumber? Don't we already have that when we graph it?

**Comment by Charlie85270** [comment]
We don't need the count, having the count attribute in each event object is out of context, the event object must contain only information about itself.

Moreover each event is indexed, we don't need to count them, we can do it directly with the result of the query (length of the array).

I used the timestamp instead of the block number because it makes multichain requests easier, there is no need to modify the request according to the requested chain. it's also easier to query data with dates as parameters.
Moreover it is the way used by all known subgraphs (https://thegraph.com/hosted-service/subgraph/ensdomains/ens, https://thegraph.com/hosted-service/subgraph/uniswap/uniswap-v2, .....)

**Comment by Charlie85270** [comment]
I'll add tests to verify that all event are well indexed.

**Comment by posix4e** [comment]
Let's verify this doesn't break existing dashboard and deploy.

**Review by posix4e — APPROVED** [review]

**Pull request merged**
