### PR TITLE
Skale implementation

### PR DESCRIPTION
**Pull request by AzizBardi**
Skale implementation

### CODE REVIEW

**Comment by foufrix** [comment]
Hi @AzizBardi 
This commit seems to have way too much change, only truffle.js and subgraph should have changed, like this PR :https://github.com/humanprotocol/hmt-escrow/pull/354/

**Comment by AzizBardi** [comment]
Hello@foufrix 

Truffle.js package.js and docker files were changed to make the project work.
These changes were necessary to make the project work.

**Comment by foufrix** [comment]
You've pushed a change with 104 files changes, where there is only 2 needed, you need to clean this PR or it will be rejected.

**Review by foufrix — CHANGES_REQUESTED** [review]
Too much files changed, 
The commit need to be cleaned

**Pull request closed without merging**
